import { useEffect, useState } from "react";
import { ArrowRight, ChevronLeft, ChevronRight, ShoppingBag } from "lucide-react";
import SiteHeader from "@/components/SiteHeader";

const storage = { hero: "/manus-storage/foodking-uae-hero_3cd168e9.png", burger: "https://foodking-react.vercel.app/assets/img/food/burger.png", pizza: "https://foodking-react.vercel.app/assets/img/food/pizza.png", combo: "https://foodking-react.vercel.app/assets/img/food/french-fry.png" };
const slides = [
  { eyebrow: "Crispy, every bite taste", title: "Delicious\nfried chicken", note: "From AED 29", image: storage.hero },
  { eyebrow: "Made hot for Dubai nights", title: "Big taste.\nZero waiting.", note: "Combos from AED 34", image: storage.combo },
  { eyebrow: "A slice of the good life", title: "Pizza that\nmeans business.", note: "Family boxes from AED 49", image: storage.pizza },
];
const categories = [
  { label: "Crispy chicken", count: "12 dishes", image: storage.hero }, { label: "Smash burgers", count: "8 dishes", image: storage.burger }, { label: "Loaded pizza", count: "10 dishes", image: storage.pizza }, { label: "Feast combos", count: "6 dishes", image: storage.combo },
];
const dishes = [
  { name: "The Foodking Box", type: "Chicken · fries · drink", price: "AED 39", image: "https://foodking-react.vercel.app/assets/img/food/french-fry.png", tag: "Best seller" }, { name: "Crispy Crown Burger", type: "Chicken · cheese · house sauce", price: "AED 29", image: "https://foodking-react.vercel.app/assets/img/food/burger.png", tag: "New" }, { name: "Dubai Heat Pizza", type: "Pepperoni · jalapeño · cheese", price: "AED 49", image: "https://foodking-react.vercel.app/assets/img/food/pizza.png", tag: "Spicy" },
];

export default function Home() {
  const [slide, setSlide] = useState(0); const [cart, setCart] = useState(0); const active = slides[slide];
  useEffect(() => { const timer = window.setInterval(() => setSlide((current) => (current + 1) % slides.length), 5800); return () => window.clearInterval(timer); }, []);
  return <div className="site-shell"><SiteHeader cartCount={cart} onCartClick={() => window.location.assign("/shop")} /><main>
    <section className="hero-section"><div className="hero-text" key={slide}><span className="eyebrow">{active.eyebrow}</span><h1>{active.title.split("\n").map((line) => <span key={line}>{line}</span>)}</h1><p>{active.note} <span>·</span> Delivery in 30–45 mins</p><a className="order-button" href="/shop">Order now <ArrowRight size={16} /></a></div><div className="hero-art" key={`art-${slide}`}><img src={active.image} alt="Foodking signature meal" /></div><div className="hero-watermark">FAST<br />FOOD</div><div className="hero-flame flame-one">✦</div><div className="hero-flame flame-two">◌</div><div className="hero-controls"><button onClick={() => setSlide((slide - 1 + slides.length) % slides.length)} aria-label="Previous slide"><ChevronLeft /></button><span>0{slide + 1} <i>/ 0{slides.length}</i></span><button onClick={() => setSlide((slide + 1) % slides.length)} aria-label="Next slide"><ChevronRight /></button></div></section>
    <div className="marquee"><div className="marquee-track"><span>5 products</span><b>✦</b><span>Pro pizza</span><b>✦</b><span>Made for sharing</span><b>✦</b><span>5 products</span><b>✦</b><span>Pro pizza</span><b>✦</b><span>Made for sharing</span><b>✦</b></div></div>
    <section className="section categories-section"><div className="section-heading"><div><span className="eyebrow red">Pick your mood</span><h2>Something<br /><em>for everyone.</em></h2></div><a className="text-link" href="/shop">See full menu <ArrowRight size={18} /></a></div><div className="category-grid">{categories.map((category, index) => <a className="category-card reveal" style={{ animationDelay: `${index * 80}ms` }} href="/shop" key={category.label}><div className="category-image"><img src={category.image} alt={category.label} /></div><div className="category-meta"><div><span>{category.count}</span><h3>{category.label}</h3></div><ArrowRight /></div></a>)}</div></section>
    <section className="offer-section"><div className="offer-copy"><span className="eyebrow">The UAE’s happiest deal</span><h2>Bring the<br /><strong>whole crew.</strong></h2><p>Two mains, loaded sides, and a little extra sauce. Built for table-sized appetites.</p><a className="order-button" href="/shop">See family combos <ArrowRight size={16} /></a></div><div className="offer-disc">50<span>%</span><small>off</small></div><img src={storage.combo} alt="Foodking family combo" /></section>
    <section className="section dishes-section"><div className="section-heading"><div><span className="eyebrow red">Popular dishes</span><h2>Don’t just take<br /><em>our word for it.</em></h2></div><div className="heading-note">Big flavor, fast delivery,<br />zero boring bites.</div></div><div className="dish-grid">{dishes.map((dish, index) => <article className="dish-card reveal" style={{ animationDelay: `${index * 90}ms` }} key={dish.name}><div className="dish-image"><span>{dish.tag}</span><img src={dish.image} alt={dish.name} /></div><div className="dish-content"><div><h3>{dish.name}</h3><p>{dish.type}</p></div><div className="dish-bottom"><strong>{dish.price}</strong><button onClick={() => setCart((n) => n + 1)} aria-label={`Add ${dish.name} to cart`}><ShoppingBag size={17} /></button></div></div></article>)}</div></section>
    <section className="story-section"><div className="story-image"><img src={storage.burger} alt="Crispy Foodking burger" /></div><div className="story-copy"><span className="eyebrow">The Foodking way</span><h2>Fast food.<br /><em>Slow care.</em></h2><p>We turn up the heat, layer in the good stuff, and send every order out with the kind of energy that makes a regular night feel like a celebration.</p><a className="text-link light" href="/contact">Meet the kitchen <ArrowRight size={18} /></a></div></section>
  </main><footer className="footer"><div className="footer-top"><a className="brand light-brand" href="/"><span>FOOD<span>KING</span></span></a><p>Bold food. Fast delivery.<br />Made for the UAE.</p><div className="footer-contact"><span>Order line</span><a href="tel:+97145000000">+971 4 500 0000</a></div></div><div className="footer-bottom"><span>© 2026 Foodking UAE</span><span>Dubai · Abu Dhabi · Sharjah</span><span>Instagram · TikTok · WhatsApp</span></div></footer></div>;
}
