import { ArrowRight, CheckCircle2, ShieldCheck, Sparkles } from "lucide-react";
import { InteractiveWorkspaceExperience } from "../components/InteractiveWorkspaceExperience";
import { useLanguage } from "../contexts/LanguageContext";

export function ProductExperiencePage() {
  const { t } = useLanguage();
  return <main className="bg-[#f5f7fb] text-[#172033]">
    <section className="relative isolate overflow-hidden px-5 pb-12 pt-20 lg:px-8 lg:pt-28"><div aria-hidden="true" className="softec-orbit softec-orbit-left" /><div aria-hidden="true" className="softec-orbit softec-orbit-right" /><div className="relative mx-auto max-w-5xl text-center"><p className="text-xs font-bold tracking-[.18em] text-[#0f766e]">{t("MAINTAINR PRODUCT EXPERIENCE", "تجربة منتج Maintainr")}</p><h1 className="mx-auto mt-5 max-w-4xl text-5xl font-semibold leading-[.96] tracking-[-.07em] text-[#172033] sm:text-6xl lg:text-7xl">{t("Choose a role and work through a real maintenance flow.", "اختر دوراً واعمل عبر مسار صيانة حقيقي.")}</h1><p className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-[#526176]">{t("This dedicated experience lets you explore the Manager, Resident, Technician, and Owner workflows without a login. Every interaction is isolated to your browser session.", "تتيح لك هذه التجربة المخصصة استكشاف مسارات المدير والساكن والفني والمالك دون تسجيل دخول. كل تفاعل معزول داخل جلسة متصفحك.")}</p><a href="#interactive-workspace" className="mt-9 inline-flex min-h-12 items-center gap-2 rounded-full bg-[#0f766e] px-6 text-sm font-semibold text-white shadow-[0_14px_30px_rgba(15,118,110,.22)] transition hover:-translate-y-0.5 hover:bg-[#115e59]"><Sparkles size={16}/>{t("Start the experience", "ابدأ التجربة")}<ArrowRight size={16}/></a><div className="mx-auto mt-12 grid max-w-3xl gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-[#cde7e3] bg-white p-4 text-start"><ShieldCheck className="text-[#0f766e]" size={19}/><p className="mt-4 text-sm font-semibold">{t("Safe session", "جلسة آمنة")}</p><p className="mt-2 text-xs leading-5 text-[#526176]">{t("No live records or customer accounts.", "دون سجلات حية أو حسابات عملاء.")}</p></div><div className="rounded-2xl border border-[#cde7e3] bg-white p-4 text-start"><CheckCircle2 className="text-[#0f766e]" size={19}/><p className="mt-4 text-sm font-semibold">{t("Working actions", "إجراءات عاملة")}</p><p className="mt-2 text-xs leading-5 text-[#526176]">{t("Create, assign, progress, resolve, and acknowledge.", "أنشئ وعيّن وحدّث وحلّ وأكّد.")}</p></div><div className="rounded-2xl border border-[#cde7e3] bg-white p-4 text-start"><Sparkles className="text-[#0f766e]" size={19}/><p className="mt-4 text-sm font-semibold">{t("Four portals", "أربع بوابات")}</p><p className="mt-2 text-xs leading-5 text-[#526176]">{t("A focused view for every operational role.", "عرض مركز لكل دور تشغيلي.")}</p></div></div></div></section>
    <InteractiveWorkspaceExperience />
  </main>;
}
