import { Building2, CalendarClock, Play, Quote } from "lucide-react";
import { useLanguage } from "../contexts/LanguageContext";
import { saasDestination } from "../lib/commercialRouting";

export function CommercialConversionRail() {
  const { t } = useLanguage();
  const saasUrl = import.meta.env.VITE_SAAS_APP_URL;
  return <aside aria-label={t("Maintainr evaluation paths", "مسارات تقييم Maintainr")} className="fixed inset-x-3 bottom-3 z-[60] mx-auto flex max-w-5xl items-center justify-between gap-2 rounded-2xl border border-slate-200/90 bg-white/95 p-2 shadow-2xl shadow-slate-900/15 backdrop-blur-xl dark:border-white/10 dark:bg-[#101522]/95 dark:shadow-black/40 sm:inset-x-5 sm:gap-3 sm:p-2.5"><a href="/demo" className="inline-flex min-h-10 flex-1 items-center justify-center gap-2 rounded-xl px-2 text-xs font-semibold text-teal-800 transition hover:bg-teal-50 dark:text-cyan-100 dark:hover:bg-cyan-300/10 sm:px-3 sm:text-sm"><Play size={15}/><span className="hidden sm:inline">{t("Explore demo", "استكشف العرض")}</span><span className="sm:hidden">{t("Demo", "عرض")}</span></a><a href="/quote?intent=demo" className="inline-flex min-h-10 flex-1 items-center justify-center gap-2 rounded-xl border border-teal-200 bg-teal-50 px-2 text-xs font-semibold text-teal-800 transition hover:bg-teal-100 dark:border-cyan-300/25 dark:bg-cyan-300/10 dark:text-cyan-100 dark:hover:bg-cyan-300/20 sm:px-3 sm:text-sm"><CalendarClock size={15}/><span>{t("Request demo", "اطلب عرضاً")}</span></a><a href="/quote?intent=quote" className="inline-flex min-h-10 flex-1 items-center justify-center gap-2 rounded-xl bg-slate-950 px-2 text-xs font-semibold text-white transition hover:bg-violet-700 dark:bg-violet-400 dark:text-[#090b12] dark:hover:bg-violet-300 sm:px-3 sm:text-sm"><Quote size={15}/><span>{t("Request quote", "اطلب عرض سعر")}</span></a><a href={saasDestination(saasUrl, "/sign-in")} className="hidden min-h-10 items-center justify-center gap-2 rounded-xl px-3 text-xs font-semibold text-slate-600 transition hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-white/[.06] lg:inline-flex"><Building2 size={15}/>{t("Customer portal", "بوابة العملاء")}</a></aside>;
}
