import { motion, useReducedMotion } from "framer-motion";
import { ArrowRight, Building2, Check, ClipboardCheck, FileCheck2, Globe2, Quote, Route, ShieldCheck, Wrench } from "lucide-react";
import { useLanguage } from "../contexts/LanguageContext";

const visuals = { hero: "/images/maintainr-hero-command-center.webp", roles: "/images/maintainr-role-coordination.webp", trust: "/images/maintainr-trust-boundary.webp" };
const rise = { hidden: { opacity: 0, y: 18 }, visible: { opacity: 1, y: 0 } };

function Action({ href, children, ghost = false }: { href: string; children: React.ReactNode; ghost?: boolean }) { return <a href={href} className={ghost ? "inline-flex min-h-11 items-center gap-2 border-b border-white/40 pb-1 text-sm font-semibold text-white transition hover:border-white" : "inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[#d7f7f1] px-5 text-sm font-semibold text-[#083b38] transition hover:bg-white active:scale-[.97]"}>{children}</a>; }

export function CommercialHomeExperience() {
  const { t } = useLanguage(); const reduce = useReducedMotion();
  const journey = [{ icon: ClipboardCheck, title: t("Capture the context", "سجل السياق"), body: t("A request begins with the detail the next person needs.", "يبدأ الطلب بالتفاصيل التي يحتاجها الشخص التالي.") }, { icon: Route, title: t("Direct the work", "وجّه العمل"), body: t("Ownership and priority are visible without extra messages.", "تظهر الملكية والأولوية دون رسائل إضافية.") }, { icon: FileCheck2, title: t("Keep the proof", "احتفظ بالإثبات"), body: t("Completion and history stay with the work they explain.", "يبقى الإنجاز والسجل مع العمل الذي يشرحانه.") }];
  return <main className="maintainr-v3 overflow-hidden bg-[#f3f1ec] text-[#10212a]">
    <section className="maintainr-v3-hero relative overflow-hidden bg-[#0b1720] text-white"><div className="maintainr-v3-grid absolute inset-0 opacity-35" /><div className="relative mx-auto grid min-h-[680px] max-w-7xl gap-12 px-5 py-16 lg:grid-cols-[.88fr_1.12fr] lg:items-center lg:px-8 lg:py-24"><div><p className="text-xs font-bold tracking-[.18em] text-[#a5eee2]">{t("PROPERTY MAINTENANCE, WITH CONTROL", "صيانة العقارات، بتحكم كامل")}</p><h1 className="mt-6 max-w-xl text-5xl font-medium leading-[.98] tracking-[-.07em] sm:text-6xl lg:text-7xl">{t("Make every maintenance decision easier to see.", "اجعل كل قرار صيانة أسهل في الرؤية.")}</h1><p className="mt-7 max-w-lg text-lg leading-8 text-slate-300">{t("Maintainr turns reports, assignments, field updates, and verified completion into one operating rhythm for property teams.", "يحول Maintainr البلاغات والتعيينات والتحديثات الميدانية والإنجاز الموثق إلى إيقاع تشغيلي واحد لفرق العقارات.")}</p><div className="mt-9 flex flex-col gap-4 sm:flex-row"><Action href="/quote"><Quote size={16} />{t("Plan your workflow", "خطط لمسار عملك")}</Action><Action href="/product" ghost>{t("Explore the platform", "استكشف المنصة")}<ArrowRight size={16} /></Action></div><div className="mt-14 flex max-w-lg gap-7 border-t border-white/15 pt-5 text-xs text-slate-300"><span>{t("English + Arabic", "العربية والإنجليزية")}</span><span>{t("Role-aware", "حسب الدور")}</span><span>{t("Built for mobile", "مصمم للجوال")}</span></div></div><motion.div initial={{ opacity: 0, y: reduce ? 0 : 26 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7, ease: [0.23, 1, .32, 1] }} className="relative"><div className="absolute -inset-5 rounded-[2.5rem] border border-white/15" /><div className="relative overflow-hidden rounded-[2rem] border border-white/20 bg-[#d7f7f1] p-2 shadow-[0_35px_100px_rgba(0,0,0,.35)]"><img src={visuals.hero} alt={t("Maintainr operations workspace", "مساحة عمل عمليات Maintainr")} className="block aspect-[16/10] w-full rounded-[1.55rem] object-cover" /><div className="absolute start-7 top-7 rounded-full bg-[#0b1720] px-3 py-1.5 text-[10px] font-bold tracking-[.14em] text-white">{t("LIVE OPERATING VIEW", "عرض تشغيلي مباشر")}</div><motion.div animate={reduce ? undefined : { y: [0, -8, 0] }} transition={{ duration: 4.6, repeat: Infinity, ease: "easeInOut" }} className="absolute bottom-7 end-7 flex items-center gap-2 rounded-2xl bg-white px-3 py-2 text-xs font-semibold text-[#0b5f57] shadow-xl"><Check size={15} />{t("Completion retained", "تم حفظ الإنجاز")}</motion.div></div></motion.div></div></section>
    <section className="border-b border-[#d8d3ca] bg-[#f3f1ec]"><div className="mx-auto grid max-w-7xl gap-px px-5 sm:grid-cols-3 lg:px-8">{[{ a: t("ONE RECORD", "سجل واحد"), b: t("Request to resolution", "من الطلب إلى الحل") }, { a: t("FOUR EXPERIENCES", "أربع تجارب"), b: t("Manager, resident, technician, owner", "مدير وساكن وفني ومالك") }, { a: t("TWO LANGUAGES", "لغتان"), b: t("English and Arabic with RTL", "العربية والإنجليزية مع RTL") }].map(item => <div key={item.a} className="border-x border-[#d8d3ca] px-6 py-7 first:border-s-0 last:border-e-0"><p className="text-[10px] font-bold tracking-[.16em] text-[#0b756d]">{item.a}</p><p className="mt-2 text-sm font-medium">{item.b}</p></div>)}</div></section>
    <section className="mx-auto grid max-w-7xl gap-12 px-5 py-24 lg:grid-cols-[.72fr_1.28fr] lg:items-start lg:px-8"><div><p className="text-xs font-bold tracking-[.16em] text-[#0b756d]">{t("THE OPERATING THREAD", "مسار التشغيل")}</p><h2 className="mt-5 text-4xl font-medium leading-[1.03] tracking-[-.055em] sm:text-5xl">{t("Work should not disappear between people.", "لا يجب أن يضيع العمل بين الأشخاص.")}</h2><p className="mt-6 max-w-md leading-7 text-[#526176]">{t("The best property operations do not rely on memory or message chains. They give every handoff a visible owner, decision, and outcome.", "لا تعتمد أفضل عمليات العقارات على الذاكرة أو سلاسل الرسائل. بل تمنح كل تسليم مالكاً وقراراً ونتيجة مرئية.")}</p></div><div className="grid gap-3">{journey.map(({ icon: Icon, title, body }, index) => <motion.article initial={{ opacity: 0, x: reduce ? 0 : 18 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, amount: .25 }} transition={{ delay: index * .08 }} key={title} className="group grid gap-5 border-t border-[#cfc8bd] py-6 sm:grid-cols-[3rem_1fr_auto] sm:items-center"><span className="grid size-11 place-items-center rounded-full border border-[#87cfc5] text-[#0b756d]"><Icon size={19} /></span><div><h3 className="text-xl font-semibold">{title}</h3><p className="mt-2 max-w-xl text-sm leading-6 text-[#526176]">{body}</p></div><span className="text-sm font-medium text-[#0b756d]">0{index + 1}</span></motion.article>)}</div></section>
    <section className="bg-[#d7f7f1]"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-8"><div className="overflow-hidden rounded-[2rem] bg-[#0b1720] p-3"><img src={visuals.roles} alt={t("Role specific Maintainr experience", "تجربة Maintainr الخاصة بالدور")} className="block w-full rounded-[1.4rem]" /></div><div><p className="text-xs font-bold tracking-[.16em] text-[#0b756d]">{t("DESIGNED FOR PARTICIPATION", "مصمم للمشاركة")}</p><h2 className="mt-5 max-w-lg text-4xl font-medium leading-[1.03] tracking-[-.055em] sm:text-5xl">{t("A calm interface for every role in the operation.", "واجهة هادئة لكل دور في العملية.")}</h2><p className="mt-6 max-w-lg leading-7 text-[#315653]">{t("Managers coordinate the portfolio. Residents report with confidence. Technicians execute with context. Owners stay informed without being overwhelmed.", "ينسق المديرون المحفظة. يبلغ السكان بثقة. ينفذ الفنيون بسياق. ويبقى الملاك على اطلاع دون إرهاق.")}</p><a href="/solutions" className="mt-8 inline-flex items-center gap-2 border-b border-[#0b756d] pb-1 text-sm font-semibold text-[#0b756d]">{t("See the role experiences", "شاهد تجارب الأدوار")}<ArrowRight size={16} /></a></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="rounded-[2rem] bg-[#0b1720] p-8 text-white sm:p-12"><div className="grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-xs font-bold tracking-[.16em] text-[#a5eee2]">{t("A BETTER STARTING POINT", "نقطة بداية أفضل")}</p><h2 className="mt-5 max-w-2xl text-4xl font-medium leading-[1.03] tracking-[-.055em] sm:text-5xl">{t("Build an operation that can show its work.", "ابنِ عملية يمكنها إظهار عملها.")}</h2><p className="mt-5 max-w-xl leading-7 text-slate-300">{t("Tell us how maintenance moves through your portfolio, and we will help you shape the right operating workflow.", "أخبرنا كيف تتحرك الصيانة عبر محفظتك وسنساعدك على تشكيل مسار العمل التشغيلي المناسب.")}</p></div><Action href="/quote"><Quote size={16} />{t("Talk to us", "تحدث إلينا")}</Action></div></div></section>
  </main>;
}
