import { motion } from "framer-motion";
import { ArrowRight, Building2, CheckCircle2, ClipboardCheck, Clock3, Eye, FileCheck2, Play, Quote, Route, ShieldCheck, Sparkles, UsersRound, Wrench } from "lucide-react";
import { useLanguage } from "../contexts/LanguageContext";

const artwork = {
  hero: "/images/maintainr-hero-command-center.webp",
  roles: "/images/maintainr-role-coordination.webp",
  trust: "/images/maintainr-trust-boundary.webp",
};

function PrimaryLink({ href, children, tone = "primary" }: { href: string; children: React.ReactNode; tone?: "primary" | "white" }) {
  const className = tone === "primary"
    ? "maintainr-primary-action inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#6d28d9] px-5 text-sm font-semibold text-white shadow-[0_16px_30px_rgba(109,40,217,.24)] transition hover:-translate-y-0.5 hover:bg-[#5b21b6] active:scale-[.97] dark:bg-[#0f766e] dark:text-white dark:hover:bg-[#115e59]"
    : "inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-5 text-sm font-semibold text-slate-800 shadow-sm transition hover:-translate-y-0.5 hover:border-cyan-300 hover:bg-cyan-50 active:scale-[.97] dark:border-white/15 dark:bg-white/[.06] dark:text-white dark:hover:bg-white/[.12]";
  return <a href={href} className={className}>{children}</a>;
}

export function CommercialHomeExperience() {
  const { t } = useLanguage();
  const steps = [
    { icon: ClipboardCheck, eyebrow: t("01 · CAPTURE", "01 · سجّل"), title: t("Report once", "بلّغ مرة واحدة"), body: t("Residents add the issue, access notes, and relevant evidence in one clear request.", "يضيف السكان المشكلة وملاحظات الوصول والأدلة ذات الصلة في طلب واحد واضح.") },
    { icon: Wrench, eyebrow: t("02 · COORDINATE", "02 · نسّق"), title: t("Move work with context", "حرّك العمل بسياقه"), body: t("Managers assign the next owner while technicians update the visible maintenance record.", "يسند المديرون المالك التالي بينما يحدّث الفنيون سجل الصيانة المرئي.") },
    { icon: FileCheck2, eyebrow: t("03 · VERIFY", "03 · تحقّق"), title: t("Retain proof", "احتفظ بالإثبات"), body: t("Notes and completion evidence remain attached to the work for accountable follow-up.", "تبقى الملاحظات وأدلة الإنجاز مرتبطة بالعمل من أجل متابعة مسؤولة.") },
  ];

  const rolePoints = [
    t("Managers coordinate priorities", "ينسق المديرون الأولويات"),
    t("Residents follow their requests", "يتابع السكان طلباتهم"),
    t("Technicians complete with proof", "ينجز الفنيون العمل مع الإثبات"),
    t("Owners stay informed without noise", "يبقى الملاك على اطلاع دون ضوضاء"),
  ];

  return <main className="commercial-mobile-safe overflow-hidden bg-[#f5f7fb] pb-28 text-[#172033] dark:bg-[#080a12] dark:text-white">
    <section className="relative isolate overflow-hidden border-b border-slate-200/80 bg-[radial-gradient(circle_at_6%_35%,rgba(34,211,238,.14),transparent_26%),radial-gradient(circle_at_93%_8%,rgba(196,181,253,.32),transparent_27%),linear-gradient(135deg,#ffffff_0%,#f7faff_54%,#eef2ff_100%)] dark:border-white/[.07] dark:bg-[radial-gradient(circle_at_6%_35%,rgba(34,211,238,.12),transparent_26%),radial-gradient(circle_at_93%_8%,rgba(139,92,246,.20),transparent_27%),linear-gradient(135deg,#080a12_0%,#101423_100%)]">
      <div className="mx-auto grid max-w-7xl gap-10 px-5 py-14 sm:py-20 lg:grid-cols-[.88fr_1.12fr] lg:items-center lg:gap-14 lg:px-8 lg:py-24">
        <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .48 }}>
          <div className="inline-flex items-center gap-2 rounded-full border border-cyan-300/50 bg-cyan-50/80 px-3 py-1.5 text-[11px] font-bold tracking-[.13em] text-cyan-800 dark:border-cyan-300/20 dark:bg-cyan-300/[.07] dark:text-cyan-100"><span className="size-1.5 rounded-full bg-cyan-500 shadow-[0_0_12px_#22d3ee]"/>{t("PROPERTY MAINTENANCE, CONNECTED", "صيانة عقارية مترابطة")}</div>
          <h1 className="mt-6 max-w-3xl text-balance text-5xl font-semibold leading-[.98] tracking-[-.065em] text-[#11192c] sm:text-6xl lg:text-7xl dark:text-white">{t("Maintenance becomes clear when every handoff has context.", "تصبح الصيانة واضحة عندما يحمل كل تسليم سياقه.")}</h1>
          <p className="mt-7 max-w-xl text-lg leading-8 text-slate-600 dark:text-slate-300">{t("Maintainr gives property teams one accountable operating record—from the first report to verified completion, in English or Arabic.", "يوفر Maintainr لفرق العقارات سجلاً تشغيلياً واحداً ومسؤولاً، من أول بلاغ حتى الإنجاز الموثق، بالعربية أو الإنجليزية.")}</p>
          <div className="mt-8 flex flex-col gap-3 sm:flex-row"><PrimaryLink href="/demo"><Play size={16} fill="currentColor"/>{t("Explore the demo", "استكشف العرض")}</PrimaryLink><PrimaryLink href="/quote" tone="white"><Quote size={17}/>{t("Request a quote", "اطلب عرض سعر")}</PrimaryLink></div>
          <p className="mt-4 text-xs leading-5 text-slate-500 dark:text-slate-400">{t("The demo uses fictional activity. A customer workspace remains private to its organization.", "يستخدم العرض نشاطاً خيالياً. تبقى مساحة عمل العميل خاصة بمؤسسته.")}</p>
        </motion.div>

        <motion.div initial={{ opacity: 0, scale: .97, y: 14 }} animate={{ opacity: 1, scale: 1, y: 0 }} transition={{ duration: .58, delay: .08 }} className="relative">
          <div className="absolute -inset-7 rounded-[3rem] bg-cyan-200/35 blur-3xl dark:bg-cyan-400/10"/>
          <div className="relative overflow-hidden rounded-[2rem] border border-white/80 bg-white shadow-[0_28px_80px_rgba(70,65,130,.16)] dark:border-white/10 dark:bg-[#101423]">
            <img src={artwork.hero} alt="" className="maintainr-product-illustration block aspect-[16/10] w-full object-cover"/>
            <div className="absolute start-[5%] top-[7%] rounded-full border border-cyan-300/40 bg-white/90 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.14em] text-cyan-800 shadow-lg backdrop-blur dark:border-cyan-300/30 dark:bg-slate-950/75 dark:text-cyan-100"><span className="me-2 inline-block size-1.5 rounded-full bg-cyan-400"/>{t("Connected workflow", "مسار عمل مترابط")}</div>
            <div className="absolute bottom-[7%] end-[5%] flex items-center gap-2 rounded-2xl border border-emerald-200 bg-white/92 px-3 py-2.5 text-[10px] font-bold uppercase tracking-[.12em] text-emerald-700 shadow-xl backdrop-blur dark:border-emerald-300/20 dark:bg-slate-950/75 dark:text-emerald-200"><span className="grid size-7 place-items-center rounded-lg bg-emerald-400 text-emerald-950"><CheckCircle2 size={15}/></span>{t("Proof retained", "تم حفظ الإثبات")}</div>
          </div>
        </motion.div>
      </div>
    </section>

    <section className="maintainr-ops-thread border-b border-slate-800 bg-[#101423] py-14 text-white dark:border-white/[.07]"><div className="mx-auto grid max-w-7xl gap-8 px-5 lg:grid-cols-[.72fr_1.28fr] lg:items-center lg:px-8"><div><p className="text-[11px] font-bold tracking-[.16em] text-cyan-200">{t("OPERATIONAL CLARITY", "وضوح تشغيلي")}</p><h2 className="mt-3 max-w-md text-3xl font-semibold tracking-[-.045em] sm:text-4xl">{t("One request becomes a visible operating thread.", "يتحول الطلب الواحد إلى مسار تشغيلي مرئي.")}</h2><p className="mt-4 max-w-lg leading-7 text-slate-300">{t("The people may change, but the context, next action, and evidence remain attached to the same maintenance record.", "قد يتغير الأشخاص، لكن السياق والإجراء التالي والإثبات تظل مرتبطة بسجل الصيانة نفسه.")}</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{ icon: ClipboardCheck, label: t("Report", "بلّغ"), note: t("Context captured", "تم تسجيل السياق") }, { icon: Route, label: t("Route", "وجّه"), note: t("Next owner clear", "المالك التالي واضح") }, { icon: Wrench, label: t("Complete", "أنجز"), note: t("Field update visible", "التحديث الميداني ظاهر") }, { icon: Eye, label: t("Review", "راجع"), note: t("Proof stays linked", "الإثبات يبقى مرتبطاً") }].map(({ icon: Icon, label, note }, index) => <div key={label} className="relative rounded-2xl border border-white/15 bg-white/[.08] p-4 backdrop-blur"><span className="grid size-9 place-items-center rounded-xl bg-cyan-300 text-[#101423]"><Icon size={17}/></span><p className="mt-6 text-[10px] font-bold tracking-[.14em] text-cyan-200">0{index + 1}</p><p className="mt-1 font-semibold text-white">{label}</p><p className="mt-1 text-xs leading-5 text-slate-300">{note}</p>{index < 3 ? <span className="absolute -end-2 top-1/2 hidden size-4 -translate-y-1/2 rotate-45 border-e border-t border-violet-300 xl:block"/> : null}</div>)}</div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8">
      <div className="grid gap-8 lg:grid-cols-[.58fr_1fr] lg:items-end"><div><p className="text-xs font-bold tracking-[.16em] text-cyan-700 dark:text-cyan-200">{t("THE MAINTENANCE JOURNEY", "رحلة الصيانة")}</p><h2 className="mt-3 max-w-md text-4xl font-semibold tracking-[-.05em] text-[#11192c] dark:text-white">{t("One powerful record from problem to proof.", "سجل قوي واحد من المشكلة إلى الإثبات.")}</h2></div><p className="max-w-2xl text-base leading-7 text-slate-600 dark:text-slate-300">{t("Maintainr prevents the important detail from disappearing between resident, manager, technician, and owner. Every step shows the next action and a durable history.", "يمنع Maintainr التفاصيل المهمة من الضياع بين الساكن والمدير والفني والمالك. تعرض كل خطوة الإجراء التالي وسجلاً دائماً.")}</p></div>
      <div className="mt-10 grid gap-4 md:grid-cols-3">{steps.map(({ icon: Icon, eyebrow, title, body }, index) => <motion.article key={title} initial={{ opacity: 0, y: 14 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .3 }} transition={{ delay: index * .06 }} className="group overflow-hidden rounded-3xl border border-slate-200 bg-white p-6 shadow-[0_12px_30px_rgba(15,23,42,.05)] transition hover:-translate-y-1 hover:border-[#b6d7cd] hover:shadow-[0_18px_40px_rgba(20,63,59,.12)] dark:border-white/[.09] dark:bg-[#101423] dark:hover:border-[#b6d7cd]/30"><span className="grid size-11 place-items-center rounded-2xl bg-[#e7f0ed] text-[#0f514b] dark:bg-[#d9bc82]/15 dark:text-[#d9bc82]"><Icon size={20}/></span><p className="mt-7 text-[10px] font-bold tracking-[.15em] text-[#0f766e] dark:text-[#b6d7cd]">{eyebrow}</p><h3 className="mt-2 text-xl font-semibold text-[#162033] dark:text-white">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-400">{body}</p><div className="mt-7 h-1 w-16 rounded-full bg-gradient-to-r from-[#75b6a4] to-[#d9bc82]"/></motion.article>)}</div>
    </section>

    <section className="border-y border-slate-200 bg-white py-20 dark:border-white/[.07] dark:bg-[#0b0e18]"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[1.08fr_.92fr] lg:items-center lg:px-8"><div className="relative"><div className="absolute -inset-6 rounded-[2.5rem] bg-violet-200/35 blur-3xl dark:bg-violet-500/10"/><img src={artwork.roles} alt="" className="maintainr-product-illustration relative block w-full rounded-[2rem] border border-slate-100 bg-slate-50 shadow-[0_24px_60px_rgba(30,41,59,.12)] dark:border-white/[.08] dark:bg-[#101423]"/></div><div><p className="text-xs font-bold tracking-[.16em] text-cyan-700 dark:text-cyan-200">{t("CLEAR FOR EVERY ROLE", "واضح لكل دور")}</p><h2 className="mt-3 max-w-xl text-4xl font-semibold tracking-[-.05em] text-[#11192c] dark:text-white">{t("Every person sees the work that matters to them.", "يرى كل شخص العمل الذي يهمه.")}</h2><p className="mt-5 max-w-xl leading-7 text-slate-600 dark:text-slate-300">{t("Maintainr keeps one maintenance record shared but makes the next action simple for each participant—without forcing everybody into the same complicated screen.", "يحافظ Maintainr على سجل صيانة مشترك، لكنه يجعل الإجراء التالي بسيطاً لكل مشارك دون فرض شاشة معقدة واحدة على الجميع.")}</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{rolePoints.map((point, index) => <div key={point} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm font-medium text-slate-700 dark:border-white/[.08] dark:bg-white/[.035] dark:text-slate-200"><span className="grid size-7 shrink-0 place-items-center rounded-lg bg-cyan-100 text-cyan-700 dark:bg-cyan-300/10 dark:text-cyan-200">{index === 0 ? <UsersRound size={15}/> : index === 1 ? <Clock3 size={15}/> : index === 2 ? <Wrench size={15}/> : <Sparkles size={15}/>}</span>{point}</div>)}</div><a href="/solutions" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-violet-700 transition hover:gap-3 dark:text-violet-200">{t("See role-based solutions", "اطلع على الحلول حسب الدور")}<ArrowRight size={16}/></a></div></div></section>

    <section className="mx-auto grid max-w-7xl gap-10 px-5 py-20 lg:grid-cols-[.88fr_1.12fr] lg:items-center lg:px-8"><div><p className="text-xs font-bold tracking-[.16em] text-cyan-700 dark:text-cyan-200">{t("TRUST BY DESIGN", "الثقة حسب التصميم")}</p><h2 className="mt-3 max-w-xl text-4xl font-semibold tracking-[-.05em] text-[#11192c] dark:text-white">{t("Your organization owns its workspace. The demo never becomes your data.", "تمتلك مؤسستك مساحة عملها. ولا يتحول العرض أبداً إلى بياناتك.")}</h2><p className="mt-5 max-w-xl leading-7 text-slate-600 dark:text-slate-300">{t("The public site explains the product. The demo uses fictional isolated activity. Each real customer organization has its own scoped workspace, identity, and maintenance record.", "يشرح الموقع العام المنتج. ويستخدم العرض نشاطاً خيالياً معزولاً. وتملك كل مؤسسة عميلة حقيقية مساحة عمل محددة النطاق وهويتها وسجل صيانتها.")}</p><div className="mt-7 space-y-3">{[t("Organization-scoped records and role access", "سجلات محصورة بالمؤسسة ووصول حسب الدور"), t("Bilingual English and Arabic with RTL support", "العربية والإنجليزية مع دعم اتجاه الكتابة من اليمين إلى اليسار"), t("Separate public, demo, and customer-workspace boundaries", "حدود منفصلة للموقع العام والعرض ومساحة عمل العميل")].map(line => <div key={line} className="flex items-center gap-3 text-sm font-medium text-slate-700 dark:text-slate-200"><span className="grid size-8 place-items-center rounded-lg bg-emerald-100 text-emerald-700 dark:bg-emerald-300/10 dark:text-emerald-200"><ShieldCheck size={16}/></span>{line}</div>)}</div></div><div className="relative"><div className="absolute -inset-6 rounded-[2.5rem] bg-cyan-200/30 blur-3xl dark:bg-cyan-500/10"/><img src={artwork.trust} alt="" className="maintainr-product-illustration relative block w-full rounded-[2rem] border border-slate-100 bg-slate-50 shadow-[0_24px_60px_rgba(30,41,59,.12)] dark:border-white/[.08] dark:bg-[#101423]"/></div></section>

    <section className="mx-auto max-w-7xl px-5 pb-20 lg:px-8"><div className="overflow-hidden rounded-[2rem] border border-violet-200 bg-[radial-gradient(circle_at_84%_0%,rgba(34,211,238,.23),transparent_28%),linear-gradient(120deg,#ede9fe_0%,#fafaff_60%,#effcff_100%)] p-7 sm:p-10 dark:border-violet-300/20 dark:bg-[radial-gradient(circle_at_84%_0%,rgba(34,211,238,.13),transparent_28%),linear-gradient(120deg,rgba(91,33,182,.36),rgba(16,19,31,.96))]"><p className="text-xs font-bold tracking-[.16em] text-violet-700 dark:text-violet-200">{t("START WITH THE RIGHT PATH", "ابدأ بالمسار المناسب")}</p><div className="mt-4 grid gap-7 lg:grid-cols-[1fr_auto] lg:items-end"><div><h2 className="max-w-2xl text-3xl font-semibold tracking-[-.05em] text-[#11192c] sm:text-4xl dark:text-white">{t("See the workflow first. Talk through your portfolio when you are ready.", "اطلع على سير العمل أولاً. ثم تحدث عن محفظتك عندما تكون جاهزاً.")}</h2><p className="mt-4 max-w-xl text-sm leading-6 text-slate-600 dark:text-slate-300">{t("Choose a safe product tour or a tailored quotation. No public customer portal appears on this site.", "اختر جولة منتج آمنة أو عرض سعر مناسباً. لا تظهر بوابة عميل عامة في هذا الموقع.")}</p></div><div className="flex flex-col gap-3 sm:flex-row"><PrimaryLink href="/demo"><Play size={16} fill="currentColor"/>{t("Explore demo", "استكشف العرض")}</PrimaryLink><PrimaryLink href="/quote" tone="white"><Quote size={17}/>{t("Request quote", "اطلب عرض سعر")}</PrimaryLink></div></div></div></section>
  </main>;
}
