import { motion, useReducedMotion } from "framer-motion";
import { ArrowDown, ArrowRight, Check, ClipboardCheck, FileCheck2, Quote, Route, Wrench } from "lucide-react";
import { useLanguage } from "../contexts/LanguageContext";

const visual = { command: "/images/maintainr-hero-command-center.webp", roles: "/images/maintainr-role-coordination.webp", trust: "/images/maintainr-trust-boundary.webp" };

function LightAction({ href, children }: { href: string; children: React.ReactNode }) { return <a href={href} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-[#d7f7f1] px-6 text-sm font-semibold text-[#083b38] transition hover:bg-white active:scale-[.97]">{children}</a>; }

export function CommercialHomeExperience() {
  const { t } = useLanguage(); const reduce = useReducedMotion();
  const stages = [{ icon: ClipboardCheck, number: "01", title: t("Report with context", "أبلغ بسياق"), body: t("The request starts with the detail the next person needs.", "يبدأ الطلب بالتفاصيل التي يحتاجها الشخص التالي.") }, { icon: Route, number: "02", title: t("Route with clarity", "وجّه بوضوح"), body: t("Ownership and priority are easy to see without a message chain.", "تظهر الملكية والأولوية بسهولة دون سلسلة رسائل.") }, { icon: FileCheck2, number: "03", title: t("Retain the proof", "احتفظ بالإثبات"), body: t("Completion evidence remains attached to the work it explains.", "يبقى إثبات الإنجاز مرتبطاً بالعمل الذي يشرحه.") }];
  return <main className="maintainr-v3 overflow-hidden bg-[#f3f1ec] text-[#10212a]">
    <section className="maintainr-v3-hero relative overflow-hidden bg-[#0b1720] px-5 pb-0 pt-16 text-white sm:pt-24"><div className="maintainr-v3-grid absolute inset-0 opacity-35" /><div className="relative mx-auto max-w-7xl"><div className="mx-auto max-w-4xl text-center"><p className="text-xs font-bold tracking-[.2em] text-[#a5eee2]">{t("PROPERTY OPERATIONS, MADE VISIBLE", "عمليات عقارية مرئية")}</p><h1 className="mt-6 text-5xl font-medium leading-[.94] tracking-[-.075em] sm:text-6xl lg:text-8xl">{t("A clearer line from request to result.", "مسار أوضح من الطلب إلى النتيجة.")}</h1><p className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-slate-300">{t("Maintainr brings the work, decisions, field updates, and evidence into one shared maintenance operating system.", "يجمع Maintainr العمل والقرارات والتحديثات الميدانية والإثبات في نظام تشغيلي واحد مشترك للصيانة.")}</p><div className="mt-9 flex flex-col justify-center gap-4 sm:flex-row"><LightAction href="/quote"><Quote size={16} />{t("Plan your workflow", "خطط لمسار عملك")}</LightAction><a href="#operating-thread" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full border border-white/25 px-6 text-sm font-semibold transition hover:bg-white/10">{t("See how it works", "شاهد كيف يعمل")}<ArrowDown size={16} /></a></div></div><motion.div initial={{ opacity: 0, y: reduce ? 0 : 32 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .72, ease: [0.23, 1, .32, 1] }} className="relative mx-auto mt-16 max-w-6xl"><div className="absolute -inset-x-8 bottom-0 top-12 rounded-t-[3rem] border border-white/15" /><div className="relative overflow-hidden rounded-t-[2.1rem] border border-[#b9eee6] bg-[#d7f7f1] p-2 shadow-[0_-14px_70px_rgba(82,239,217,.12)]"><img src={visual.command} alt={t("Maintainr property operations interface", "واجهة Maintainr لعمليات العقارات")} className="block aspect-[16/8] w-full rounded-t-[1.65rem] object-cover" /><span className="absolute start-8 top-8 rounded-full bg-[#0b1720] px-3 py-1.5 text-[10px] font-bold tracking-[.14em] text-white">{t("MAINTAINR WORKSPACE", "مساحة عمل Maintainr")}</span><motion.span animate={reduce ? undefined : { y: [0, -7, 0] }} transition={{ duration: 4.8, repeat: Infinity, ease: "easeInOut" }} className="absolute bottom-8 end-8 flex items-center gap-2 rounded-2xl bg-white px-3 py-2 text-xs font-semibold text-[#0b756d] shadow-xl"><Check size={15} />{t("Completion verified", "تم التحقق من الإنجاز")}</motion.span></div></motion.div></div></section>
    <section className="relative z-10 mx-auto -mt-px max-w-7xl bg-[#f3f1ec] px-5 py-8 lg:px-8"><div className="grid gap-3 border-y border-[#cfc8bd] py-4 sm:grid-cols-3"><p className="text-sm font-medium">{t("One operational record", "سجل تشغيلي واحد")}</p><p className="text-sm font-medium">{t("Four role-focused experiences", "أربع تجارب تركز على الدور")}</p><p className="text-sm font-medium">{t("English and Arabic, designed for RTL", "العربية والإنجليزية مصممة لـ RTL")}</p></div></section>
    <section id="operating-thread" className="mx-auto grid max-w-7xl gap-12 px-5 py-24 lg:grid-cols-[.55fr_1.45fr] lg:px-8"><div className="lg:pt-12"><p className="text-xs font-bold tracking-[.16em] text-[#0b756d]">{t("THE OPERATING THREAD", "مسار التشغيل")}</p><h2 className="mt-5 text-4xl font-medium leading-[1.02] tracking-[-.06em] sm:text-5xl">{t("Maintenance moves faster when the next action is obvious.", "تتحرك الصيانة أسرع عندما يكون الإجراء التالي واضحاً.")}</h2><a href="/features" className="mt-8 inline-flex items-center gap-2 border-b border-[#0b756d] pb-1 text-sm font-semibold text-[#0b756d]">{t("Explore the workflow", "استكشف مسار العمل")}<ArrowRight size={16} /></a></div><div className="grid gap-0 border-t border-[#cfc8bd] md:grid-cols-3 md:border-s">{stages.map(({ icon: Icon, number, title, body }) => <article key={number} className="border-b border-[#cfc8bd] p-7 md:border-e md:border-b-0"><span className="text-xs font-bold tracking-[.16em] text-[#0b756d]">{number}</span><Icon className="mt-16 text-[#0b756d]" size={24} /><h3 className="mt-5 text-2xl font-semibold">{title}</h3><p className="mt-4 text-sm leading-6 text-[#526176]">{body}</p></article>)}</div></section>
    <section className="bg-[#d7f7f1]"><div className="mx-auto grid max-w-7xl gap-0 px-5 lg:grid-cols-[1.1fr_.9fr] lg:px-8"><div className="py-20 lg:py-28"><p className="text-xs font-bold tracking-[.16em] text-[#0b756d]">{t("ROLE-READY", "جاهز للأدوار")}</p><h2 className="mt-5 max-w-xl text-4xl font-medium leading-[1.02] tracking-[-.06em] sm:text-5xl">{t("One system, without asking every person to work the same way.", "نظام واحد دون مطالبة كل شخص بالعمل بالطريقة نفسها.")}</h2><p className="mt-6 max-w-lg leading-7 text-[#315653]">{t("Managers coordinate. Residents report. Technicians execute. Owners stay informed. Every experience is focused on the action that matters next.", "ينسق المديرون. يبلغ السكان. ينفذ الفنيون. يبقى الملاك على اطلاع. تركز كل تجربة على الإجراء التالي المهم.")}</p><LightAction href="/solutions"><Wrench size={16} />{t("See the role views", "شاهد عروض الأدوار")}</LightAction></div><div className="relative min-h-96 overflow-hidden bg-[#0b1720]"><img src={visual.roles} alt={t("Maintainr role-based views", "عروض Maintainr حسب الدور")} className="absolute inset-0 h-full w-full object-cover" /></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="grid overflow-hidden rounded-[2rem] bg-[#0b1720] text-white lg:grid-cols-[.7fr_1.3fr]"><div className="p-8 sm:p-12"><p className="text-xs font-bold tracking-[.16em] text-[#a5eee2]">{t("THE RIGHT START", "البداية الصحيحة")}</p><h2 className="mt-5 text-4xl font-medium leading-[1.02] tracking-[-.06em]">{t("Plan a maintenance operation people can trust.", "خطط لعملية صيانة يمكن للناس الوثوق بها.")}</h2><p className="mt-5 text-sm leading-7 text-slate-300">{t("Talk through your portfolio, roles, and current operating flow with the Maintainr team.", "ناقش محفظتك وأدوارك ومسار التشغيل الحالي مع فريق Maintainr.")}</p><div className="mt-8"><LightAction href="/quote"><Quote size={16} />{t("Talk to us", "تحدث إلينا")}</LightAction></div></div><div className="relative min-h-72"><img src={visual.trust} alt="" className="absolute inset-0 h-full w-full object-cover opacity-85" /></div></div></section>
  </main>;
}
