import { useMemo, useState } from "react";
import { ArrowRight, BellRing, CalendarDays, CheckCircle2, ClipboardList, LayoutDashboard, MessageSquareText, PlayCircle, RotateCcw, Send, Sparkles, Wrench, X } from "lucide-react";
import { useLanguage } from "../contexts/LanguageContext";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "./ui/dialog";

type PreviewTab = "overview" | "requests" | "schedule" | "updates";
type TicketState = "OPEN" | "IN_PROGRESS" | "RESOLVED";

const initialTickets = [
  { id: "MT-204", title: "Water pressure issue", unit: "A-204", priority: "HIGH", state: "OPEN" as TicketState },
  { id: "MT-110", title: "Air-conditioning service", unit: "B-110", priority: "MEDIUM", state: "IN_PROGRESS" as TicketState },
  { id: "MT-034", title: "Lobby light replacement", unit: "Lobby", priority: "LOW", state: "RESOLVED" as TicketState },
];

function TicketPill({ state }: { state: TicketState }) {
  const styles: Record<TicketState, string> = { OPEN: "bg-rose-50 text-rose-700", IN_PROGRESS: "bg-amber-50 text-amber-800", RESOLVED: "bg-emerald-50 text-emerald-700" };
  return <span className={`rounded-full px-2.5 py-1 text-[10px] font-bold tracking-[.1em] ${styles[state]}`}>{state.replace("_", " ")}</span>;
}

export function HeroInteractivePreview() {
  const { t } = useLanguage();
  const [open, setOpen] = useState(false);
  const [tab, setTab] = useState<PreviewTab>("overview");
  const [tickets, setTickets] = useState(initialTickets);
  const [visitAdded, setVisitAdded] = useState(false);
  const [message, setMessage] = useState("");
  const [sentMessage, setSentMessage] = useState("");
  const [notice, setNotice] = useState(t("Preview ready. Nothing here changes a live workspace.", "المعاينة جاهزة. لا شيء هنا يغير مساحة عمل حية."));

  const stats = useMemo(() => ({ open: tickets.filter(ticket => ticket.state === "OPEN").length, active: tickets.filter(ticket => ticket.state === "IN_PROGRESS").length, resolved: tickets.filter(ticket => ticket.state === "RESOLVED").length }), [tickets]);
  const reset = () => { setTab("overview"); setTickets(initialTickets); setVisitAdded(false); setMessage(""); setSentMessage(""); setNotice(t("Preview reset to the starting workflow.", "تمت إعادة تعيين المعاينة إلى مسار العمل الابتدائي.")); };
  const updateTicket = (id: string, state: TicketState) => { setTickets(current => current.map(ticket => ticket.id === id ? { ...ticket, state } : ticket)); setNotice(state === "IN_PROGRESS" ? t("Work started. The request is now visible as in progress.", "بدأ العمل. أصبح الطلب الآن مرئياً كقيد التنفيذ.") : t("Work resolved. The completion is retained in the preview record.", "تم حل العمل. تم الاحتفاظ بالإنجاز في سجل المعاينة.")); };
  const send = () => { const trimmed = message.trim(); if (!trimmed) return; setSentMessage(trimmed); setMessage(""); setNotice(t("Update sent to the preview activity feed.", "تم إرسال التحديث إلى موجز نشاط المعاينة.")); };
  const tabs: { id: PreviewTab; label: string; icon: typeof LayoutDashboard }[] = [
    { id: "overview", label: t("Overview", "نظرة عامة"), icon: LayoutDashboard },
    { id: "requests", label: t("Requests", "الطلبات"), icon: ClipboardList },
    { id: "schedule", label: t("Schedule", "الجدولة"), icon: CalendarDays },
    { id: "updates", label: t("Updates", "التحديثات"), icon: MessageSquareText },
  ];

  return <Dialog open={open} onOpenChange={setOpen}>
    <DialogTrigger asChild>
      <button type="button" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full border border-slate-300 bg-white px-6 text-sm font-semibold text-[#172033] shadow-[0_10px_22px_rgba(23,32,51,.06)] transition hover:-translate-y-0.5 hover:border-[#0f766e] hover:text-[#0f766e] active:scale-[.97]"><PlayCircle size={17} />{t("Try the live preview", "جرّب المعاينة المباشرة")}</button>
    </DialogTrigger>
    <DialogContent showCloseButton={false} className="max-h-[calc(100dvh-1rem)] w-[calc(100vw-1rem)] max-w-6xl overflow-hidden rounded-[1.7rem] border border-[#b9e7df] bg-[#f4f8f7] p-0 text-[#172033] shadow-[0_30px_90px_rgba(7,38,36,.35)] sm:w-[calc(100vw-2rem)]">
      <DialogHeader className="sr-only"><DialogTitle>{t("Maintainr live dashboard preview", "معاينة لوحة تحكم Maintainr المباشرة")}</DialogTitle><DialogDescription>{t("A safe local preview of the Maintainr maintenance workflow.", "معاينة محلية آمنة لمسار صيانة Maintainr.")}</DialogDescription></DialogHeader>
      <div className="flex max-h-[calc(100dvh-1rem)] min-h-[34rem] flex-col sm:max-h-[min(46rem,calc(100dvh-2rem))]">
        <header className="flex shrink-0 items-center justify-between border-b border-[#d9e8e5] bg-white px-4 py-3 sm:px-6"><div className="flex min-w-0 items-center gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-2xl bg-[#0f766e] text-white shadow-lg shadow-teal-700/20"><Wrench size={19} /></span><div className="min-w-0"><p className="truncate text-sm font-semibold">Maintainr</p><p className="mt-0.5 truncate text-[10px] font-bold tracking-[.16em] text-[#0f766e]">{t("LIVE WORKFLOW PREVIEW", "معاينة مسار عمل مباشر")}</p></div></div><div className="flex items-center gap-2"><span className="hidden rounded-full bg-[#eaf8f5] px-3 py-1.5 text-[11px] font-semibold text-[#0f766e] sm:inline-flex">{t("Sample data only", "بيانات نموذجية فقط")}</span><DialogClose asChild><button type="button" aria-label={t("Close preview", "إغلاق المعاينة")} className="grid size-10 place-items-center rounded-xl border border-[#d9e8e5] bg-white text-slate-600 transition hover:border-[#0f766e] hover:text-[#0f766e]"><X size={18} /></button></DialogClose></div></header>
        <div className="flex min-h-0 flex-1 flex-col lg:flex-row">
          <aside className="shrink-0 border-b border-[#d9e8e5] bg-[#0b1720] p-3 text-slate-300 lg:w-52 lg:border-b-0 lg:border-r lg:p-4"><p className="hidden px-3 pb-3 text-[10px] font-bold tracking-[.18em] text-teal-200 lg:block">{t("WORKSPACE", "مساحة العمل")}</p><nav className="flex gap-1 overflow-x-auto lg:grid">{tabs.map(({ id, label, icon: Icon }) => <button key={id} type="button" onClick={() => { setTab(id); setNotice(`${label} ${t("workspace opened.", "تم فتح مساحة العمل.")}`); }} aria-current={tab === id ? "page" : undefined} className={`flex min-h-11 shrink-0 items-center gap-2 rounded-xl px-3 text-sm transition ${tab === id ? "bg-[#ecfdf8] font-semibold text-[#0f766e]" : "text-slate-300 hover:bg-white/[.08] hover:text-white"}`}><Icon size={16} />{label}</button>)}</nav><a href="/experience" className="mt-3 hidden items-center gap-2 rounded-xl border border-white/15 px-3 py-2.5 text-xs font-semibold text-white transition hover:bg-white/[.08] lg:flex">{t("Open full experience", "افتح التجربة الكاملة")}<ArrowRight size={14} /></a></aside>
          <section className="min-h-0 flex-1 overflow-y-auto overscroll-contain p-4 sm:p-6"><p className="sr-only" aria-live="polite">{notice}</p>{tab === "overview" && <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold tracking-[.16em] text-[#0f766e]">{t("PROPERTY MANAGER", "مدير العقار")}</p><h3 className="mt-1 text-2xl font-semibold tracking-[-.04em]">{t("Maintenance overview", "نظرة عامة على الصيانة")}</h3></div><button type="button" onClick={() => setTab("requests")} className="rounded-xl border border-[#cfe0dc] bg-white px-3 py-2 text-xs font-semibold text-[#0f766e] transition hover:bg-[#f2fbf8]">{t("View requests", "عرض الطلبات")}</button></div><div className="grid gap-3 sm:grid-cols-3">{[[t("Open", "مفتوح"), stats.open, "text-rose-600"], [t("In progress", "قيد التنفيذ"), stats.active, "text-amber-700"], [t("Resolved", "تم الحل"), stats.resolved, "text-emerald-700"]].map(([label, value, color]) => <article key={String(label)} className="rounded-2xl border border-[#dce9e6] bg-white p-4"><p className="text-xs font-semibold text-slate-500">{label}</p><p className={`mt-2 text-3xl font-semibold ${color}`}>{value}</p><p className="mt-1 text-xs text-slate-500">{t("Live preview state", "حالة المعاينة المباشرة")}</p></article>)}</div><article className="overflow-hidden rounded-2xl border border-[#dce9e6] bg-white"><div className="flex items-center justify-between border-b border-[#e9f0ef] px-4 py-3"><div><p className="font-semibold">{t("Next focus", "التركيز التالي")}</p><p className="mt-1 text-xs text-slate-500">{t("A clear handoff is ready for action.", "تسليم واضح جاهز لاتخاذ إجراء.")}</p></div><BellRing size={19} className="text-[#0f766e]" /></div><div className="p-4"><p className="text-sm font-semibold">{tickets.find(ticket => ticket.state !== "RESOLVED")?.title}</p><p className="mt-1 text-sm text-slate-500">{t("Open the request to move it through the workflow.", "افتح الطلب لتحريكه عبر مسار العمل.")}</p><button type="button" onClick={() => setTab("requests")} className="mt-4 rounded-xl bg-[#0f766e] px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-[#115e59]">{t("Start the workflow", "ابدأ مسار العمل")}</button></div></article></div>}
          {tab === "requests" && <div><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold tracking-[.16em] text-[#0f766e]">{t("REQUEST OPERATIONS", "عمليات الطلبات")}</p><h3 className="mt-1 text-2xl font-semibold tracking-[-.04em]">{t("Move work forward", "حرّك العمل إلى الأمام")}</h3></div><button type="button" onClick={reset} className="inline-flex items-center gap-2 rounded-xl border border-[#cfe0dc] bg-white px-3 py-2 text-xs font-semibold text-[#0f766e]"><RotateCcw size={14} />{t("Reset preview", "إعادة تعيين المعاينة")}</button></div><div className="mt-5 space-y-3">{tickets.map(ticket => <article key={ticket.id} className="flex flex-col gap-3 rounded-2xl border border-[#dce9e6] bg-white p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{ticket.title}</p><TicketPill state={ticket.state} /></div><p className="mt-1 text-xs text-slate-500">{ticket.id} · {ticket.unit} · {ticket.priority} {t("priority", "أولوية")}</p></div>{ticket.state === "OPEN" ? <button type="button" onClick={() => updateTicket(ticket.id, "IN_PROGRESS")} className="rounded-xl bg-[#0f766e] px-3 py-2 text-xs font-semibold text-white hover:bg-[#115e59]">{t("Start work", "ابدأ العمل")}</button> : ticket.state === "IN_PROGRESS" ? <button type="button" onClick={() => updateTicket(ticket.id, "RESOLVED")} className="rounded-xl bg-[#0f766e] px-3 py-2 text-xs font-semibold text-white hover:bg-[#115e59]">{t("Mark resolved", "تحديد كمحلول")}</button> : <span className="inline-flex items-center gap-1 text-xs font-semibold text-emerald-700"><CheckCircle2 size={15} />{t("Completion retained", "تم حفظ الإنجاز")}</span>}</article>)}</div></div>}
          {tab === "schedule" && <div className="grid gap-5 lg:grid-cols-[.88fr_1.12fr]"><article className="rounded-2xl border border-[#dce9e6] bg-white p-5"><p className="text-xs font-bold tracking-[.16em] text-[#0f766e]">{t("PLAN A VISIT", "خطط لزيارة")}</p><h3 className="mt-2 text-2xl font-semibold tracking-[-.04em]">{t("Keep planned work visible", "حافظ على رؤية العمل المخطط")}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{t("Schedule a sample HVAC visit to see how future work stays connected to the operating record.", "جدول زيارة HVAC نموذجية لترى كيف يبقى العمل المستقبلي متصلاً بالسجل التشغيلي.")}</p><button type="button" onClick={() => { setVisitAdded(true); setNotice(t("Sample visit added to the preview calendar.", "تمت إضافة زيارة نموذجية إلى تقويم المعاينة.")); }} className="mt-6 rounded-xl bg-[#0f766e] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#115e59]">{t("Add 10:30 visit", "أضف زيارة 10:30")}</button></article><article className="rounded-2xl border border-[#dce9e6] bg-white p-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#eaf8f5] text-[#0f766e]"><CalendarDays size={19} /></span><div><p className="font-semibold">{t("Today’s schedule", "جدول اليوم")}</p><p className="text-xs text-slate-500">{t("Sample manager calendar", "تقويم مدير نموذجي")}</p></div></div><div className="mt-6 space-y-3"><div className="rounded-xl border border-[#dce9e6] p-3"><p className="text-xs font-bold text-[#0f766e]">09:00</p><p className="mt-1 text-sm font-semibold">{t("Review open requests", "راجع الطلبات المفتوحة")}</p></div>{visitAdded ? <div className="rounded-xl border border-[#9eddd2] bg-[#f2fffc] p-3"><p className="text-xs font-bold text-[#0f766e]">10:30</p><p className="mt-1 text-sm font-semibold">{t("HVAC visit · B-110", "زيارة HVAC · B-110")}</p><p className="mt-1 text-xs text-slate-500">{t("Added in this preview", "تمت إضافتها في هذه المعاينة")}</p></div> : <div className="rounded-xl border border-dashed border-[#cfe0dc] p-3 text-sm text-slate-500">{t("Add the next visit to see it appear here.", "أضف الزيارة التالية لرؤيتها تظهر هنا.")}</div>}</div></article></div>}
          {tab === "updates" && <div className="grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><article className="rounded-2xl border border-[#dce9e6] bg-white p-5"><p className="text-xs font-bold tracking-[.16em] text-[#0f766e]">{t("KEEP THE LOOP CLOSED", "أغلق الحلقة")}</p><h3 className="mt-2 text-2xl font-semibold tracking-[-.04em]">{t("Share a clear update", "شارك تحديثاً واضحاً")}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{t("Add a sample message to see how a project update remains visible beside the work.", "أضف رسالة نموذجية لترى كيف يبقى تحديث المشروع مرئياً بجانب العمل.")}</p><textarea value={message} onChange={event => setMessage(event.target.value)} placeholder={t("Write a sample update…", "اكتب تحديثاً نموذجياً…")} className="mt-5 min-h-28 w-full rounded-xl border border-[#cfe0dc] bg-[#f7fbfa] p-3 text-sm outline-none focus:border-[#0f766e]" /><button type="button" disabled={!message.trim()} onClick={send} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-[#0f766e] px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-[#115e59] disabled:cursor-not-allowed disabled:bg-slate-300"><Send size={16} />{t("Send update", "أرسل التحديث")}</button></article><article className="rounded-2xl border border-[#dce9e6] bg-white p-5"><p className="font-semibold">{t("Activity feed", "موجز النشاط")}</p><div className="mt-5 space-y-3"><div className="rounded-xl bg-[#f7fbfa] p-3 text-sm"><p className="font-semibold">{t("Manager", "المدير")}</p><p className="mt-1 text-slate-500">{t("Priority review is ready for the next request.", "مراجعة الأولوية جاهزة للطلب التالي.")}</p></div>{sentMessage ? <div className="rounded-xl bg-[#eaf8f5] p-3 text-sm"><p className="font-semibold text-[#0f766e]">{t("You", "أنت")}</p><p className="mt-1 text-[#315653]">{sentMessage}</p></div> : <div className="rounded-xl border border-dashed border-[#cfe0dc] p-3 text-sm text-slate-500">{t("Your sample update will appear here.", "سيظهر تحديثك النموذجي هنا.")}</div>}</div></article></div>}
          <div className="mt-6 flex flex-col justify-between gap-3 border-t border-[#dce9e6] pt-4 text-xs text-slate-500 sm:flex-row sm:items-center"><span>{t("Safe local preview · no customer data · no live changes", "معاينة محلية آمنة · لا بيانات عملاء · لا تغييرات حية")}</span><a href="/experience" className="inline-flex items-center gap-1 font-semibold text-[#0f766e]">{t("Open the full experience", "افتح التجربة الكاملة")}<ArrowRight size={14} /></a></div>
          </section>
        </div>
      </div>
    </DialogContent>
  </Dialog>;
}
