import { AnimatePresence, motion } from "framer-motion";
import { BellRing, Building2, CheckCircle2, ClipboardList, Clock3, FileText, LayoutDashboard, Menu, Plus, Send, ShieldCheck, UserRoundCheck, UsersRound, Wrench, X } from "lucide-react";
import { useMemo, useState } from "react";
import { useLanguage } from "../contexts/LanguageContext";

type Role = "manager" | "resident" | "technician" | "owner";
type Status = "OPEN" | "ASSIGNED" | "IN_PROGRESS" | "RESOLVED";
type Ticket = { id: number; title: string; detail: string; status: Status; priority: "MEDIUM" | "HIGH"; unit: string };

const roleIcons = { manager: Building2, resident: UsersRound, technician: Wrench, owner: UserRoundCheck };
const statusStyles: Record<Status, string> = { OPEN: "bg-amber-50 text-amber-800", ASSIGNED: "bg-sky-50 text-sky-700", IN_PROGRESS: "bg-violet-50 text-violet-700", RESOLVED: "bg-emerald-50 text-emerald-700" };

export function InteractiveWorkspaceExperience() {
  const { t } = useLanguage();
  const [role, setRole] = useState<Role>("manager");
  const [view, setView] = useState<"overview" | "requests" | "reminders" | "activity">("overview");
  const [mobileNav, setMobileNav] = useState(false);
  const [tickets, setTickets] = useState<Ticket[]>([
    { id: 1, title: t("Kitchen water issue", "مشكلة مياه المطبخ"), detail: t("Water is collecting under the sink. Access is available this afternoon.", "تتجمع المياه أسفل الحوض. الدخول متاح هذا بعد الظهر."), status: "OPEN", priority: "HIGH", unit: "A-204" },
    { id: 2, title: t("Hallway light check", "فحص إضاءة الممر"), detail: t("The light near the lift needs a replacement check.", "الضوء بالقرب من المصعد يحتاج إلى فحص واستبدال."), status: "ASSIGNED", priority: "MEDIUM", unit: "B-101" },
    { id: 3, title: t("Air conditioning follow-up", "متابعة التكييف"), detail: t("Completion note is ready for review.", "ملاحظة الإنجاز جاهزة للمراجعة."), status: "RESOLVED", priority: "MEDIUM", unit: "A-109" },
  ]);
  const [title, setTitle] = useState("");
  const [detail, setDetail] = useState("");
  const [notice, setNotice] = useState(t("Choose a role and try a safe workflow. Changes stay in this browser session.", "اختر دوراً وجرب مسار عمل آمن. تبقى التغييرات في جلسة المتصفح هذه."));
  const [reminderAcknowledged, setReminderAcknowledged] = useState(false);
  const labels: Record<Role, { name: string; description: string }> = {
    manager: { name: t("Property Manager", "مدير العقار"), description: t("Coordinate priorities, assignments, people, and follow-up.", "نسّق الأولويات والتعيينات والأشخاص والمتابعة.") },
    resident: { name: t("Resident", "الساكن"), description: t("Report an issue and follow its progress clearly.", "أبلغ عن مشكلة وتابع تقدمها بوضوح.") },
    technician: { name: t("Technician", "الفني"), description: t("Review work, update progress, and retain completion proof.", "راجع العمل وحدّث التقدم واحتفظ بإثبات الإنجاز.") },
    owner: { name: t("Owner", "المالك"), description: t("Review trusted maintenance history for the assigned unit.", "راجع سجل الصيانة الموثوق للوحدة المخصصة.") },
  };
  const current = labels[role];
  const RoleIcon = roleIcons[role];
  const visibleTickets = useMemo(() => role === "resident" || role === "owner" ? tickets.filter(ticket => ticket.unit === "A-204") : tickets, [role, tickets]);
  const updateStatus = (id: number, status: Status, message: string) => { setTickets(currentTickets => currentTickets.map(ticket => ticket.id === id ? { ...ticket, status } : ticket)); setNotice(message); };
  const addRequest = (event: React.FormEvent) => { event.preventDefault(); if (!title.trim() || !detail.trim()) return; setTickets(current => [{ id: Date.now(), title: title.trim(), detail: detail.trim(), status: "OPEN", priority: "MEDIUM", unit: "A-204" }, ...current]); setTitle(""); setDetail(""); setView("requests"); setNotice(t("Your request was added to this safe interactive workspace.", "تمت إضافة طلبك إلى مساحة العمل التفاعلية الآمنة.")); };
  const actionFor = (ticket: Ticket) => {
    if (role === "manager" && ticket.status === "OPEN") return <button onClick={() => updateStatus(ticket.id, "ASSIGNED", t("The request is now assigned to a technician.", "تم تعيين الطلب لفني."))} className="rounded-lg bg-[#0f766e] px-3 py-2 text-xs font-semibold text-white">{t("Assign", "تعيين")}</button>;
    if (role === "technician" && ticket.status === "ASSIGNED") return <button onClick={() => updateStatus(ticket.id, "IN_PROGRESS", t("Work is now in progress.", "العمل قيد التنفيذ الآن."))} className="rounded-lg bg-[#0f766e] px-3 py-2 text-xs font-semibold text-white">{t("Start work", "ابدأ العمل")}</button>;
    if (role === "technician" && ticket.status === "IN_PROGRESS") return <button onClick={() => updateStatus(ticket.id, "RESOLVED", t("Completion is recorded for review.", "تم تسجيل الإنجاز للمراجعة."))} className="rounded-lg bg-[#0f766e] px-3 py-2 text-xs font-semibold text-white">{t("Mark resolved", "وضع علامة تم الحل")}</button>;
    if (role === "manager" && ticket.status === "RESOLVED") return <button onClick={() => setNotice(t("The completion record is ready for management review.", "سجل الإنجاز جاهز لمراجعة الإدارة."))} className="rounded-lg border border-[#b9e7df] bg-white px-3 py-2 text-xs font-semibold text-[#0f766e]">{t("Review", "مراجعة")}</button>;
    return null;
  };
  const nav = [{ id: "overview", label: t("Overview", "نظرة عامة"), icon: LayoutDashboard }, { id: "requests", label: t("Requests", "الطلبات"), icon: ClipboardList }, { id: "reminders", label: t("Reminders", "التذكيرات"), icon: BellRing }, { id: "activity", label: t("Activity", "النشاط"), icon: Clock3 }] as const;

  return <section id="interactive-workspace" className="commercial-interactive-workspace bg-white px-5 py-24 lg:px-8">
    <div className="mx-auto max-w-7xl">
      <div className="mx-auto max-w-3xl text-center"><p className="text-xs font-bold tracking-[.18em] text-[#0f766e]">{t("INTERACTIVE WORKSPACE", "مساحة عمل تفاعلية")}</p><h2 className="mt-5 text-4xl font-semibold leading-[1.02] tracking-[-.06em] text-[#172033] sm:text-6xl">{t("Choose a role. Move the work forward.", "اختر دوراً. وادفع العمل إلى الأمام.")}</h2><p className="mx-auto mt-6 max-w-2xl leading-7 text-[#526176]">{t("This is a safe browser-based product experience. Every action works during your visit, while no live workspace, customer account, or production record is accessed.", "هذه تجربة منتج آمنة تعمل داخل المتصفح. يعمل كل إجراء أثناء زيارتك، دون الوصول إلى مساحة عمل حية أو حساب عميل أو سجل إنتاجي.")}</p></div>
      <div className="mt-10 flex flex-wrap justify-center gap-2">{(Object.keys(labels) as Role[]).map(id => { const Icon = roleIcons[id]; const selected = id === role; return <button type="button" key={id} onClick={() => { setRole(id); setView("overview"); setNotice(t(`${labels[id].name} workspace is ready.`, `مساحة عمل ${labels[id].name} جاهزة.`)); }} className={`inline-flex min-h-11 items-center gap-2 rounded-full border px-4 text-sm font-semibold transition ${selected ? "border-[#172033] bg-[#172033] text-white" : "border-slate-200 bg-white text-[#526176] hover:border-[#0f766e] hover:text-[#0f766e]"}`}><Icon size={16}/>{labels[id].name}</button>; })}</div>

      <div className="mt-10 overflow-hidden rounded-[2rem] border border-[#cde7e3] bg-[#f8fbfb] shadow-[0_26px_72px_rgba(23,32,51,.12)]">
        <div className="flex items-center justify-between border-b border-[#dcefed] bg-white px-5 py-4 lg:hidden"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#0f766e] text-white"><Wrench size={17}/></span><span className="font-semibold text-[#172033]">Maintainr</span></div><button type="button" onClick={() => setMobileNav(open => !open)} className="grid size-10 place-items-center rounded-xl border border-slate-200 text-[#172033]">{mobileNav ? <X size={18}/> : <Menu size={18}/>}</button></div>
        <div className="grid min-h-[43rem] lg:grid-cols-[15rem_1fr]">
          <aside className={`${mobileNav ? "block" : "hidden"} border-e border-[#dcefed] bg-[#effbf9] p-5 lg:block`}><div className="hidden items-center gap-3 font-semibold text-[#172033] lg:flex"><span className="grid size-10 place-items-center rounded-xl bg-[#0f766e] text-white"><Wrench size={18}/></span>Maintainr</div><div className="mt-7 rounded-2xl border border-[#cce7e3] bg-white p-4"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#d9f5f1] text-[#0f766e]"><RoleIcon size={18}/></span><div><p className="text-sm font-semibold text-[#172033]">{current.name}</p><p className="mt-1 text-xs text-[#526176]">{t("Interactive view", "عرض تفاعلي")}</p></div></div></div><nav className="mt-6 grid gap-1">{nav.map(item => { const Icon = item.icon; const selected = view === item.id; return <button type="button" key={item.id} onClick={() => { setView(item.id); setMobileNav(false); }} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-start text-sm transition ${selected ? "bg-white font-semibold text-[#172033] shadow-sm" : "text-[#526176] hover:bg-white/70 hover:text-[#172033]"}`}><Icon size={17} className={selected ? "text-[#0f766e]" : ""}/>{item.label}</button>; })}</nav><div className="mt-7 rounded-2xl bg-[#172033] p-4 text-white"><ShieldCheck size={18} className="text-[#9eece0]"/><p className="mt-4 text-xs font-semibold">{t("Safe by design", "آمن بطبيعته")}</p><p className="mt-2 text-xs leading-5 text-slate-300">{t("Session-only actions. No live records.", "إجراءات داخل الجلسة فقط. دون سجلات حية.")}</p></div></aside>
          <main className="min-w-0 p-5 sm:p-8"><div className="flex flex-col gap-4 border-b border-[#dcefed] pb-6 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold tracking-[.16em] text-[#0f766e]">{t("MAINTAINR WORKSPACE", "مساحة عمل Maintainr")}</p><h3 className="mt-2 text-2xl font-semibold text-[#172033] sm:text-3xl">{current.name}</h3><p className="mt-2 max-w-xl text-sm leading-6 text-[#526176]">{current.description}</p></div><span className="inline-flex w-fit items-center gap-2 rounded-full bg-[#d9f5f1] px-3 py-2 text-xs font-semibold text-[#0f766e]"><CheckCircle2 size={15}/>{t("Session active", "الجلسة نشطة")}</span></div>
            <AnimatePresence mode="wait"><motion.div key={`${role}-${view}`} initial={{ opacity: 0, x: 18 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -12 }} transition={{ duration: .24, ease: [0.23,1,.32,1] }} className="mt-6">
              {view === "overview" && <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3"><Metric label={t("Open work", "عمل مفتوح")} value={String(tickets.filter(ticket => ticket.status !== "RESOLVED").length)} detail={t("Needs a next action", "يحتاج إلى إجراء تالٍ")}/><Metric label={t("Ready to review", "جاهز للمراجعة")} value={String(tickets.filter(ticket => ticket.status === "RESOLVED").length)} detail={t("Retained completion", "إنجاز محفوظ")}/><Metric label={t("Your view", "عرضك")} value={current.name} detail={t("Role-aware access", "وصول حسب الدور")}/></div><div className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><div className="rounded-2xl border border-slate-100 bg-white p-5"><div className="flex items-center justify-between"><div><p className="font-semibold text-[#172033]">{t("Current requests", "الطلبات الحالية")}</p><p className="mt-1 text-xs text-[#526176]">{t("Select Requests to take the next safe action.", "اختر الطلبات لاتخاذ الإجراء الآمن التالي.")}</p></div><button onClick={() => setView("requests")} className="text-xs font-semibold text-[#0f766e]">{t("Open list", "فتح القائمة")}</button></div><div className="mt-4 grid gap-2">{visibleTickets.slice(0, 2).map(ticket => <TicketLine key={ticket.id} ticket={ticket}/>)}</div></div><div className="rounded-2xl bg-[#172033] p-5 text-white"><BellRing size={20} className="text-[#9eece0]"/><p className="mt-6 text-sm font-semibold">{t("Maintenance reminder", "تذكير صيانة")}</p><p className="mt-2 text-xs leading-5 text-slate-300">{t("Planned inspection follow-up is visible in this workspace.", "متابعة الفحص المخطط مرئية في مساحة العمل هذه.")}</p><button onClick={() => setView("reminders")} className="mt-5 text-xs font-semibold text-[#9eece0]">{t("View reminder", "عرض التذكير")}</button></div></div></div>}
              {view === "requests" && <div className="space-y-5">{role === "resident" && <form onSubmit={addRequest} className="rounded-2xl border border-[#b9e7df] bg-[#effbf9] p-5"><div className="flex items-center gap-3"><Plus size={18} className="text-[#0f766e]"/><div><p className="font-semibold text-[#172033]">{t("Report a maintenance issue", "أبلغ عن مشكلة صيانة")}</p><p className="mt-1 text-xs text-[#526176]">{t("This creates a safe in-session request for the interactive workspace.", "ينشئ هذا طلباً آمناً داخل الجلسة لمساحة العمل التفاعلية.")}</p></div></div><div className="mt-4 grid gap-3"><input required value={title} onChange={event => setTitle(event.target.value)} placeholder={t("Issue title", "عنوان المشكلة")} className="h-11 rounded-xl border border-[#b9e7df] bg-white px-3 text-sm text-[#172033] outline-none focus:border-[#0f766e]"/><textarea required value={detail} onChange={event => setDetail(event.target.value)} placeholder={t("What should the team know?", "ما الذي يجب أن يعرفه الفريق؟")} className="min-h-24 rounded-xl border border-[#b9e7df] bg-white p-3 text-sm text-[#172033] outline-none focus:border-[#0f766e]"/><button className="inline-flex h-11 w-fit items-center gap-2 rounded-xl bg-[#0f766e] px-4 text-sm font-semibold text-white"><Send size={16}/>{t("Submit request", "إرسال الطلب")}</button></div></form>}<div className="rounded-2xl border border-slate-100 bg-white"><div className="border-b border-slate-100 px-5 py-4"><p className="font-semibold text-[#172033]">{role === "owner" ? t("Unit maintenance history", "سجل صيانة الوحدة") : t("Maintenance requests", "طلبات الصيانة")}</p></div><div className="divide-y divide-slate-100">{visibleTickets.map(ticket => <div key={ticket.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-[#172033]">{ticket.title}</p><Status status={ticket.status}/></div><p className="mt-2 max-w-2xl text-sm leading-6 text-[#526176]">{ticket.detail}</p><p className="mt-2 text-xs font-medium text-[#0f766e]">{ticket.unit} · {ticket.priority === "HIGH" ? t("High priority", "أولوية عالية") : t("Standard priority", "أولوية قياسية")}</p></div>{actionFor(ticket)}</div>)}</div></div></div>}
              {view === "reminders" && <div className="rounded-2xl border border-[#b9e7df] bg-white p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold tracking-[.15em] text-[#0f766e]">{t("PLANNED FOLLOW-UP", "متابعة مخططة")}</p><h4 className="mt-2 text-xl font-semibold text-[#172033]">{t("Monthly safety inspection", "فحص السلامة الشهري")}</h4><p className="mt-3 max-w-xl text-sm leading-6 text-[#526176]">{t("A reminder view keeps planned property work near the requests the team is handling now.", "يحافظ عرض التذكير على عمل العقارات المخطط قريباً من الطلبات التي يتعامل معها الفريق الآن.")}</p></div><span className={`rounded-full px-3 py-2 text-xs font-semibold ${reminderAcknowledged ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{reminderAcknowledged ? t("Acknowledged", "تم التأكيد") : t("Upcoming", "قادم")}</span></div><button onClick={() => { setReminderAcknowledged(true); setNotice(t("The reminder was acknowledged for this interactive session.", "تم تأكيد التذكير لهذه الجلسة التفاعلية.")); }} disabled={reminderAcknowledged} className="mt-6 inline-flex h-11 items-center gap-2 rounded-xl bg-[#0f766e] px-4 text-sm font-semibold text-white disabled:cursor-default disabled:bg-slate-300"><CheckCircle2 size={16}/>{reminderAcknowledged ? t("Acknowledged", "تم التأكيد") : t("Acknowledge reminder", "تأكيد التذكير")}</button></div>}
              {view === "activity" && <div className="rounded-2xl border border-slate-100 bg-white p-6"><FileText size={22} className="text-[#0f766e]"/><p className="mt-5 text-xs font-bold tracking-[.15em] text-[#0f766e]">{t("SESSION ACTIVITY", "نشاط الجلسة")}</p><p className="mt-3 text-xl font-semibold text-[#172033]">{notice}</p><p className="mt-4 max-w-2xl text-sm leading-6 text-[#526176]">{t("Try assigning, progressing, resolving, submitting, or acknowledging work. Your interactions are intentionally isolated to this browser session.", "جرّب تعيين العمل أو تحديثه أو حله أو إرساله أو تأكيده. تفاعلاتك معزولة عمداً في جلسة المتصفح هذه.")}</p></div>}
            </motion.div></AnimatePresence>
          </main>
        </div>
      </div>
    </div>
  </section>;
}

function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className="rounded-2xl border border-slate-100 bg-white p-5"><p className="text-xs font-bold tracking-[.13em] text-[#526176]">{label}</p><p className="mt-4 text-2xl font-semibold text-[#172033]">{value}</p><p className="mt-2 text-xs text-[#526176]">{detail}</p></article>; }
function Status({ status }: { status: Status }) { const { t } = useLanguage(); const labels: Record<Status, string> = { OPEN: t("Open", "مفتوح"), ASSIGNED: t("Assigned", "تم التعيين"), IN_PROGRESS: t("In progress", "قيد التنفيذ"), RESOLVED: t("Resolved", "تم الحل") }; return <span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${statusStyles[status]}`}>{labels[status]}</span>; }
function TicketLine({ ticket }: { ticket: Ticket }) { return <div className="flex items-center justify-between gap-3 rounded-xl bg-[#f8fbfb] p-3"><div className="min-w-0"><p className="truncate text-sm font-semibold text-[#172033]">{ticket.title}</p><p className="mt-1 text-xs text-[#526176]">{ticket.unit}</p></div><Status status={ticket.status}/></div>; }
